### ISSUE TITLE
Cannot start already started MediaProjection

### ISSUE THREAD

**Issue by CarLoOSX** [ankyl/castscreen#4]
Hi ankyl

It seems that something has broken suddenly. This was working two days ago.

When I try to connect to chomecast this is what I get:

E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.xxxx.xxxxx, PID: 27217
        java.lang.IllegalStateException: **Cannot start already started MediaProjection**
        at android.os.Parcel.readException(Parcel.java)
        at android.os.Parcel.readException(Parcel.java)
        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java)
        at android.media.projection.MediaProjection.<init>(MediaProjection.java)
        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java)
        at github.ankyl.castscreen.ProjectionManager.<init>(ProjectionManager.java:28)
        at github.ankyl.castscreen.ConnectionManager.<init>(ConnectionManager.java:55)
        at github.ankyl.castscreen.CastScreenService.initialize(CastScreenService.java:79)
        at github.ankyl.castscreen.CastScreenService.access$000(CastScreenService.java:23)
        at github.ankyl.castscreen.CastScreenService$1.onServiceConnected(CastScreenService.java:55)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java)
        at android.os.Handler.handleCallback(Handler.java)
        at android.os.Handler.dispatchMessage(Handler.java)
        at android.os.Looper.loop(Looper.java)
        at android.app.ActivityThread.main(ActivityThread.java)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

Thank you again!

**Comment by ankyl** [comment]
Fixed by #5.
